name: Security Scanning

on:
  schedule:
    # Run daily at midnight
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      scan_type:
        description: 'Type of scan to run'
        required: true
        default: 'full'
        type: choice
        options:
          - full
          - tfsec
          - checkov
          - trivy

jobs:
  # -----------------------------------
  # TFSec Scan
  # -----------------------------------
  tfsec:
    name: 'TFSec Scan'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.scan_type == 'full' || github.event.inputs.scan_type == 'tfsec' || github.event_name == 'schedule' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run tfsec
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          format: json,sarif,lovely
          out: tfsec-results

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: tfsec-results
          path: tfsec-results.*

  # -----------------------------------
  # Checkov Scan
  # -----------------------------------
  checkov:
    name: 'Checkov Scan'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.scan_type == 'full' || github.event.inputs.scan_type == 'checkov' || github.event_name == 'schedule' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          framework: terraform
          output_format: cli,json,junitxml,sarif
          output_file_path: console,checkov-results.json,checkov-results.xml,checkov-results.sarif
          download_external_modules: true

      - name: Upload Results
        uses: actions/upload-artifact@v4
        with:
          name: checkov-results
          path: checkov-results.*

  # -----------------------------------
  # Trivy IaC Scan
  # -----------------------------------
  trivy:
    name: 'Trivy IaC Scan'
    runs-on: ubuntu-latest
    if: ${{ github.event.inputs.scan_type == 'full' || github.event.inputs.scan_type == 'trivy' || github.event_name == 'schedule' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'config'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH,MEDIUM'

      - name: Upload Trivy Results
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: trivy-results.sarif

  # -----------------------------------
  # Security Report Summary
  # -----------------------------------
  summary:
    name: 'Generate Security Report'
    runs-on: ubuntu-latest
    needs: [tfsec, checkov, trivy]
    if: always()
    steps:
      - name: Download All Artifacts
        uses: actions/download-artifact@v4
        with:
          path: security-reports

      - name: Generate Summary
        run: |
          echo "# 🔒 Security Scan Report" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Scanner | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|---------|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| TFSec | ${{ needs.tfsec.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Checkov | ${{ needs.checkov.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Trivy | ${{ needs.trivy.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "📅 Scan Date: $(date -u)" >> $GITHUB_STEP_SUMMARY

      - name: Create Issue on Failures
        if: ${{ needs.tfsec.result == 'failure' || needs.checkov.result == 'failure' || needs.trivy.result == 'failure' }}
        uses: actions/github-script@v7
        with:
          script: |
            const title = `🚨 Security Scan Failures - ${new Date().toISOString().split('T')[0]}`;
            const body = `
            ## Security Scan Report
            
            The scheduled security scan has detected issues:
            
            | Scanner | Status |
            |---------|--------|
            | TFSec | ${{ needs.tfsec.result }} |
            | Checkov | ${{ needs.checkov.result }} |
            | Trivy | ${{ needs.trivy.result }} |
            
            Please review the [workflow run](${process.env.GITHUB_SERVER_URL}/${process.env.GITHUB_REPOSITORY}/actions/runs/${process.env.GITHUB_RUN_ID}) for details.
            `;
            
            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: title,
              body: body,
              labels: ['security', 'automated']
            });